-- PURE-ADDITIVE migration: GA support without touching training workflow.
--
-- The original attendance_logs table is owned by the training/PMES flow:
--   - application_id NOT NULL + FK to member_applications
--   - training_stage NOT NULL check constraint
-- We do NOT touch either of those.
--
-- General Assembly attendance is for already-confirmed members (no application).
-- Instead of relaxing the training schema, we create a NEW dedicated table:
--   public.general_assembly_attendance
-- keyed by (member_id, meeting_date), with its own RLS / indexes.
--
-- The MIGS scoring engine reads from THIS table (not attendance_logs) for the
-- assembly attendance criterion. Training attendance is unaffected.

CREATE TABLE IF NOT EXISTS public.general_assembly_attendance (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        UUID NOT NULL REFERENCES public.member(id) ON DELETE CASCADE,
    meeting_date     DATE NOT NULL,
    status           TEXT NOT NULL CHECK (status IN ('Present', 'Absent')),
    remarks          TEXT,
    recorded_by      UUID,
    recorded_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT general_assembly_member_date_unique UNIQUE (member_id, meeting_date)
);

CREATE INDEX IF NOT EXISTS general_assembly_attendance_member_idx
    ON public.general_assembly_attendance (member_id);

CREATE INDEX IF NOT EXISTS general_assembly_attendance_date_idx
    ON public.general_assembly_attendance (meeting_date DESC);

CREATE INDEX IF NOT EXISTS general_assembly_attendance_status_idx
    ON public.general_assembly_attendance (status);

-- RLS: staff-only read/write, mirroring attendance_logs policy style.
ALTER TABLE public.general_assembly_attendance ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS general_assembly_staff_select ON public.general_assembly_attendance;
CREATE POLICY general_assembly_staff_select
    ON public.general_assembly_attendance
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS general_assembly_staff_insert ON public.general_assembly_attendance;
CREATE POLICY general_assembly_staff_insert
    ON public.general_assembly_attendance
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS general_assembly_staff_update ON public.general_assembly_attendance;
CREATE POLICY general_assembly_staff_update
    ON public.general_assembly_attendance
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON public.general_assembly_attendance TO authenticated;
GRANT ALL ON public.general_assembly_attendance TO service_role;
