-- Run this in Supabase SQL editor.
-- Creates attendance_logs with constraints compatible with the frontend upsert.

CREATE TABLE IF NOT EXISTS public.attendance_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id TEXT NOT NULL,
  training_stage TEXT NOT NULL,
  attendance_status TEXT NOT NULL DEFAULT 'Pending',
  remarks TEXT,
  member_name TEXT,
  member_email TEXT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  recorded_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT attendance_logs_stage_check CHECK (
    training_stage IN ('1st Training')
  ),
  CONSTRAINT attendance_logs_status_check CHECK (
    attendance_status IN ('Present', 'Absent', 'Pending')
  )
);

-- Required for frontend upsert(onConflict: "application_id,training_stage")
CREATE UNIQUE INDEX IF NOT EXISTS attendance_logs_app_stage_uidx
ON public.attendance_logs (application_id, training_stage);

CREATE INDEX IF NOT EXISTS attendance_logs_recorded_at_idx
ON public.attendance_logs (recorded_at DESC);

CREATE INDEX IF NOT EXISTS attendance_logs_training_stage_idx
ON public.attendance_logs (training_stage);

CREATE OR REPLACE FUNCTION public.is_training_staff()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text;
BEGIN
  IF to_regclass('public.member_account') IS NOT NULL THEN
    SELECT lower(btrim(coalesce(ma.role, '')))
    INTO v_role
    FROM public.member_account ma
    WHERE ma.user_id = auth.uid()
       OR lower(coalesce(ma.email, '')) = lower(coalesce(auth.email(), ''))
    LIMIT 1;

    IF v_role IN ('secretary', 'bod') THEN
      RETURN true;
    END IF;
  END IF;

  IF to_regclass('public.member_accounts') IS NOT NULL THEN
    SELECT lower(btrim(coalesce(ma.role, '')))
    INTO v_role
    FROM public.member_accounts ma
    WHERE ma.user_id = auth.uid()
       OR lower(coalesce(ma.email, '')) = lower(coalesce(auth.email(), ''))
    LIMIT 1;

    IF v_role IN ('secretary', 'bod') THEN
      RETURN true;
    END IF;
  END IF;

  v_role := lower(btrim(coalesce(
    auth.jwt() ->> 'role',
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    ''
  )));

  RETURN v_role IN ('secretary', 'bod');
END;
$$;

ALTER TABLE IF EXISTS public.attendance_logs ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE ON public.attendance_logs TO authenticated;

DO $$
BEGIN
  EXECUTE 'DROP POLICY IF EXISTS attendance_staff_select ON public.attendance_logs';
  EXECUTE '
    CREATE POLICY attendance_staff_select
    ON public.attendance_logs
    FOR SELECT
    TO authenticated
    USING (public.is_training_staff())
  ';

  EXECUTE 'DROP POLICY IF EXISTS attendance_staff_insert ON public.attendance_logs';
  EXECUTE '
    CREATE POLICY attendance_staff_insert
    ON public.attendance_logs
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_training_staff())
  ';

  EXECUTE 'DROP POLICY IF EXISTS attendance_staff_update ON public.attendance_logs';
  EXECUTE '
    CREATE POLICY attendance_staff_update
    ON public.attendance_logs
    FOR UPDATE
    TO authenticated
    USING (public.is_training_staff())
    WITH CHECK (public.is_training_staff())
  ';
END $$;
