-- Run this in Supabase SQL editor.
-- Creates attendance_logs with constraints compatible with the frontend upsert.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.attendance_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id TEXT NOT NULL,
  training_stage TEXT NOT NULL,
  attendance_status TEXT NOT NULL DEFAULT 'Pending',
  remarks TEXT,
  member_name TEXT,
  member_email TEXT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  recorded_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT attendance_logs_stage_check CHECK (
    training_stage IN ('Training', '1st Training')
  ),
  CONSTRAINT attendance_logs_status_check CHECK (
    attendance_status IN ('Present', 'Absent', 'Pending')
  )
);

-- Additive fields for newer attendance design (non-breaking).
ALTER TABLE IF EXISTS public.attendance_logs
  ADD COLUMN IF NOT EXISTS attendance_id UUID,
  ADD COLUMN IF NOT EXISTS membership_number_id UUID,
  ADD COLUMN IF NOT EXISTS meeting_date DATE,
  ADD COLUMN IF NOT EXISTS meeting_type TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT;

-- Backfill additive fields from existing data where possible.
UPDATE public.attendance_logs
SET attendance_id = gen_random_uuid()
WHERE attendance_id IS NULL;

UPDATE public.attendance_logs
SET meeting_date = recorded_at::date
WHERE meeting_date IS NULL
  AND recorded_at IS NOT NULL;

-- PMES is the membership training equivalent of current '1st Training' stage.
UPDATE public.attendance_logs
SET meeting_type = 'PMES'
WHERE (meeting_type IS NULL OR btrim(meeting_type) = '')
  AND training_stage IN ('Training', '1st Training');

-- Normalize legacy value to canonical stage label used by current UI.
UPDATE public.attendance_logs
SET training_stage = 'Training'
WHERE training_stage = '1st Training';

UPDATE public.attendance_logs
SET status = attendance_status
WHERE status IS NULL
  AND attendance_status IN ('Present', 'Absent');

CREATE OR REPLACE FUNCTION public.set_attendance_meeting_type_from_stage()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF (NEW.meeting_type IS NULL OR btrim(NEW.meeting_type) = '')
      AND NEW.training_stage IN ('Training', '1st Training') THEN
    NEW.meeting_type := 'PMES';
  END IF;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_attendance_logs_meeting_type_default'
      AND tgrelid = 'public.attendance_logs'::regclass
      AND NOT tgisinternal
  ) THEN
    CREATE TRIGGER trg_attendance_logs_meeting_type_default
    BEFORE INSERT OR UPDATE OF training_stage, meeting_type
    ON public.attendance_logs
    FOR EACH ROW
    EXECUTE FUNCTION public.set_attendance_meeting_type_from_stage();
  END IF;
END $$;

-- Keep additive constraints idempotent and non-breaking to current flow.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'attendance_logs_stage_check'
      AND conrelid = 'public.attendance_logs'::regclass
  ) THEN
    ALTER TABLE public.attendance_logs
      DROP CONSTRAINT attendance_logs_stage_check;
  END IF;

  ALTER TABLE public.attendance_logs
    ADD CONSTRAINT attendance_logs_stage_check
    CHECK (training_stage IN ('Training', '1st Training'));

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'attendance_logs_meeting_type_check'
      AND conrelid = 'public.attendance_logs'::regclass
  ) THEN
    ALTER TABLE public.attendance_logs
      ADD CONSTRAINT attendance_logs_meeting_type_check
      CHECK (meeting_type IS NULL OR meeting_type IN ('GA', 'Meeting', 'PMES'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'attendance_logs_status_v2_check'
      AND conrelid = 'public.attendance_logs'::regclass
  ) THEN
    ALTER TABLE public.attendance_logs
      ADD CONSTRAINT attendance_logs_status_v2_check
      CHECK (status IS NULL OR status IN ('Present', 'Absent'));
  END IF;
END $$;

-- Optional FK: membership_number_id -> member(id)
DO $$
BEGIN
  IF to_regclass('public.member') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'attendance_logs_membership_number_fk'
         AND conrelid = 'public.attendance_logs'::regclass
     ) THEN
    ALTER TABLE public.attendance_logs
      ADD CONSTRAINT attendance_logs_membership_number_fk
      FOREIGN KEY (membership_number_id)
      REFERENCES public.member(id)
      ON DELETE SET NULL;
  END IF;
END $$;

-- Optional FK: application_id -> whichever membership application table exists.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname IN ('attendance_logs_member_applications_fk', 'attendance_logs_membership_application_fk')
      AND conrelid = 'public.attendance_logs'::regclass
  ) THEN
    RETURN;
  END IF;

  IF to_regclass('public.member_applications') IS NOT NULL THEN
    BEGIN
      ALTER TABLE public.attendance_logs
        ADD CONSTRAINT attendance_logs_member_applications_fk
        FOREIGN KEY (application_id)
        REFERENCES public.member_applications(application_id)
        ON DELETE RESTRICT
        NOT VALID;
      RETURN;
    EXCEPTION WHEN OTHERS THEN
      -- Keep script non-breaking if referenced table shape differs.
      NULL;
    END;
  END IF;

  IF to_regclass('public.membership_application') IS NOT NULL THEN
    BEGIN
      ALTER TABLE public.attendance_logs
        ADD CONSTRAINT attendance_logs_membership_application_fk
        FOREIGN KEY (application_id)
        REFERENCES public.membership_application(application_id)
        ON DELETE RESTRICT
        NOT VALID;
    EXCEPTION WHEN OTHERS THEN
      -- Keep script non-breaking if referenced table shape differs.
      NULL;
    END;
  END IF;
END $$;

-- Required for frontend upsert(onConflict: "application_id,training_stage")
CREATE UNIQUE INDEX IF NOT EXISTS attendance_logs_app_stage_uidx
ON public.attendance_logs (application_id, training_stage);

CREATE UNIQUE INDEX IF NOT EXISTS attendance_logs_attendance_uidx
ON public.attendance_logs (attendance_id);

CREATE INDEX IF NOT EXISTS attendance_logs_membership_number_idx
ON public.attendance_logs (membership_number_id);

CREATE INDEX IF NOT EXISTS attendance_logs_meeting_date_idx
ON public.attendance_logs (meeting_date DESC);

CREATE INDEX IF NOT EXISTS attendance_logs_meeting_type_idx
ON public.attendance_logs (meeting_type);

CREATE INDEX IF NOT EXISTS attendance_logs_status_v2_idx
ON public.attendance_logs (status);

CREATE INDEX IF NOT EXISTS attendance_logs_recorded_at_idx
ON public.attendance_logs (recorded_at DESC);

CREATE INDEX IF NOT EXISTS attendance_logs_training_stage_idx
ON public.attendance_logs (training_stage);

CREATE OR REPLACE FUNCTION public.is_training_staff()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text;
BEGIN
  IF to_regclass('public.member_account') IS NOT NULL THEN
    SELECT lower(btrim(coalesce(ma.role, '')))
    INTO v_role
    FROM public.member_account ma
    WHERE ma.user_id = auth.uid()
       OR lower(coalesce(ma.email, '')) = lower(coalesce(auth.email(), ''))
    LIMIT 1;

    IF v_role IN ('secretary', 'bod') THEN
      RETURN true;
    END IF;
  END IF;

  IF to_regclass('public.member_accounts') IS NOT NULL THEN
    SELECT lower(btrim(coalesce(ma.role, '')))
    INTO v_role
    FROM public.member_accounts ma
    WHERE ma.user_id = auth.uid()
       OR lower(coalesce(ma.email, '')) = lower(coalesce(auth.email(), ''))
    LIMIT 1;

    IF v_role IN ('secretary', 'bod') THEN
      RETURN true;
    END IF;
  END IF;

  v_role := lower(btrim(coalesce(
    auth.jwt() ->> 'role',
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    ''
  )));

  RETURN v_role IN ('secretary', 'bod');
END;
$$;

ALTER TABLE IF EXISTS public.attendance_logs ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE ON public.attendance_logs TO authenticated;

DO $$
BEGIN
  EXECUTE 'DROP POLICY IF EXISTS attendance_staff_select ON public.attendance_logs';
  EXECUTE '
    CREATE POLICY attendance_staff_select
    ON public.attendance_logs
    FOR SELECT
    TO authenticated
    USING (public.is_training_staff())
  ';

  EXECUTE 'DROP POLICY IF EXISTS attendance_staff_insert ON public.attendance_logs';
  EXECUTE '
    CREATE POLICY attendance_staff_insert
    ON public.attendance_logs
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_training_staff())
  ';

  EXECUTE 'DROP POLICY IF EXISTS attendance_staff_update ON public.attendance_logs';
  EXECUTE '
    CREATE POLICY attendance_staff_update
    ON public.attendance_logs
    FOR UPDATE
    TO authenticated
    USING (public.is_training_staff())
    WITH CHECK (public.is_training_staff())
  ';
END $$;
