-- Run this in Supabase SQL editor.
-- This file is for LOAN FORM RLS policies only.
-- It is intentionally separate from membership_confirmation_policies.sql.

CREATE TABLE IF NOT EXISTS public.koica_loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  control_number TEXT NOT NULL UNIQUE,
  full_name TEXT,
  credentials JSONB,
  user_email TEXT,
  loan_type_code TEXT,
  loan_amount NUMERIC,
  principal_amount NUMERIC,
  interest_rate NUMERIC,
  term INTEGER,
  loan_status TEXT NOT NULL DEFAULT 'pending',
  application_status TEXT NOT NULL DEFAULT 'pending',
  application_type TEXT NOT NULL DEFAULT 'new',
  application_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  disbursal_date TIMESTAMPTZ,
  raw_payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_koica_loans_user_email ON public.koica_loans (lower(user_email));

DO $$
BEGIN
  ALTER TABLE public.koica_loans ADD COLUMN IF NOT EXISTS full_name TEXT;
  ALTER TABLE public.koica_loans ADD COLUMN IF NOT EXISTS credentials JSONB;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'koica_loans'
      AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.koica_loans DROP COLUMN IF EXISTS user_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'koica_loans'
      AND column_name = 'member_id'
  ) THEN
    ALTER TABLE public.koica_loans DROP COLUMN IF EXISTS member_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'koica_loans'
      AND column_name = 'user_email'
      AND is_nullable = 'NO'
  ) THEN
    ALTER TABLE public.koica_loans ALTER COLUMN user_email DROP NOT NULL;
  END IF;
END $$;

ALTER TABLE IF EXISTS consolidated_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS emergency_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bonus_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS koica_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS co_makers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS loan_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS member ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.loan_types ADD COLUMN IF NOT EXISTS code TEXT;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'loans'
      AND column_name = 'member_id'
      AND is_nullable = 'NO'
  ) THEN
    ALTER TABLE public.loans ALTER COLUMN member_id DROP NOT NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.loan_types') IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.loan_types WHERE lower(coalesce(name, '')) IN ('bonus', 'bonus loan')) THEN
      INSERT INTO public.loan_types (code, name) VALUES ('BONUS', 'Bonus Loan');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.loan_types WHERE lower(coalesce(name, '')) IN ('consolidated', 'consolidated loan')) THEN
      INSERT INTO public.loan_types (code, name) VALUES ('CONSOLIDATED', 'Consolidated Loan');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.loan_types WHERE lower(coalesce(name, '')) IN ('emergency', 'emergency loan')) THEN
      INSERT INTO public.loan_types (code, name) VALUES ('EMERGENCY', 'Emergency Loan');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.loan_types WHERE lower(coalesce(name, '')) IN ('koica', 'koica loan', 'agri-business financial facility loan', 'abff loan')) THEN
      INSERT INTO public.loan_types (code, name) VALUES ('KOICA', 'ABFF Loan');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.loan_types WHERE lower(coalesce(name, '')) IN ('nonmember bonus loan', 'non-member bonus loan', 'non member bonus loan')) THEN
      INSERT INTO public.loan_types (code, name) VALUES ('NONMEMBER_BONUS', 'Nonmember Bonus Loan');
    END IF;

    UPDATE public.loan_types
    SET code = 'BONUS'
    WHERE lower(coalesce(name, '')) IN ('bonus', 'bonus loan')
      AND (code IS NULL OR btrim(code) = '');

    UPDATE public.loan_types
    SET code = 'CONSOLIDATED'
    WHERE lower(coalesce(name, '')) IN ('consolidated', 'consolidated loan')
      AND (code IS NULL OR btrim(code) = '');

    UPDATE public.loan_types
    SET code = 'EMERGENCY'
    WHERE lower(coalesce(name, '')) IN ('emergency', 'emergency loan')
      AND (code IS NULL OR btrim(code) = '');

    UPDATE public.loan_types
    SET code = 'KOICA'
    WHERE lower(coalesce(name, '')) IN ('koica', 'koica loan', 'agri-business financial facility loan', 'abff loan')
      AND (code IS NULL OR btrim(code) = '');

    UPDATE public.loan_types
    SET code = 'NONMEMBER_BONUS'
    WHERE lower(coalesce(name, '')) IN ('nonmember bonus loan', 'non-member bonus loan', 'non member bonus loan')
      AND (code IS NULL OR btrim(code) = '');
  END IF;
END $$;

-- Co-maker schema support for both members and non-members.
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_name TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_email TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_mobile TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_address TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_id_no TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS is_member BOOLEAN NOT NULL DEFAULT false;

DO $$
DECLARE
  existing_pk_name text;
BEGIN
  IF to_regclass('public.co_makers') IS NOT NULL THEN
    -- Drop any existing primary key (name can vary: co_makers_pk / co_makers_pkey / etc.).
    SELECT conname
    INTO existing_pk_name
    FROM pg_constraint
    WHERE conrelid = 'public.co_makers'::regclass
      AND contype = 'p'
    LIMIT 1;

    IF existing_pk_name IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.co_makers DROP CONSTRAINT %I', existing_pk_name);
    END IF;

    -- Backfill id for existing rows before creating new PK.
    EXECUTE 'UPDATE public.co_makers SET id = DEFAULT WHERE id IS NULL';

    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'co_makers_id_pk'
        AND conrelid = 'public.co_makers'::regclass
    ) THEN
      EXECUTE 'ALTER TABLE public.co_makers ADD CONSTRAINT co_makers_id_pk PRIMARY KEY (id)';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'co_makers'
        AND column_name = 'member_id'
        AND is_nullable = 'NO'
    ) THEN
      EXECUTE 'ALTER TABLE public.co_makers ALTER COLUMN member_id DROP NOT NULL';
    END IF;
  END IF;
END $$;

DROP INDEX IF EXISTS idx_co_makers_loan_member_unique;
CREATE INDEX IF NOT EXISTS idx_co_makers_loan_member_idx
ON public.co_makers (loan_id, member_id);

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON public.loan_types TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.loans TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.koica_loans TO authenticated;
GRANT INSERT ON public.koica_loans TO anon;
GRANT SELECT, INSERT, UPDATE ON public.co_makers TO authenticated;
GRANT SELECT ON public.member TO authenticated;

CREATE OR REPLACE FUNCTION public.has_portal_role(
  p_user_id uuid,
  p_email text,
  p_roles text[]
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  matched boolean := false;
BEGIN
  IF to_regclass('public.member_account') IS NOT NULL THEN
    EXECUTE '
      SELECT EXISTS (
        SELECT 1
        FROM public.member_account ma
        WHERE (
          ma.user_id = $1
          OR lower(coalesce(ma.email, '''')) = lower(coalesce($2, ''''))
        )
          AND lower(coalesce(ma.role, '''')) = ANY ($3)
      )
    '
    INTO matched
    USING p_user_id, p_email, p_roles;

    IF matched THEN
      RETURN true;
    END IF;
  END IF;

  IF to_regclass('public.member_accounts') IS NOT NULL THEN
    EXECUTE '
      SELECT EXISTS (
        SELECT 1
        FROM public.member_accounts ma
        WHERE (
          ma.user_id = $1
          OR lower(coalesce(ma.email, '''')) = lower(coalesce($2, ''''))
        )
          AND lower(coalesce(ma.role, '''')) = ANY ($3)
      )
    '
    INTO matched
    USING p_user_id, p_email, p_roles;

    IF matched THEN
      RETURN true;
    END IF;
  END IF;

  RETURN false;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.loan_types') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated read loan types" ON loan_types';
    EXECUTE 'CREATE POLICY "authenticated read loan types" ON loan_types FOR SELECT TO authenticated USING (true)';

    EXECUTE 'DROP POLICY IF EXISTS "service role all loan types" ON loan_types';
    EXECUTE 'CREATE POLICY "service role all loan types" ON loan_types FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')';
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.koica_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "anon insert koica loans" ON koica_loans';
    EXECUTE '
      CREATE POLICY "anon insert koica loans"
      ON koica_loans
      FOR INSERT
      TO anon
      WITH CHECK (true)
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own koica loans" ON koica_loans';
    EXECUTE '
      CREATE POLICY "authenticated insert own koica loans"
      ON koica_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (
        lower(coalesce(user_email, '''')) = lower(auth.email())
        AND lower(coalesce(loan_type_code, '''')) = ''koica''
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert nonmember bonus loans" ON koica_loans';
    EXECUTE '
      CREATE POLICY "authenticated insert nonmember bonus loans"
      ON koica_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (
        lower(coalesce(loan_type_code, '''')) = ''nonmember_bonus''
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own koica loans" ON koica_loans';
    EXECUTE '
      CREATE POLICY "authenticated read own koica loans"
      ON koica_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "staff read all koica loans" ON koica_loans';
    EXECUTE '
      CREATE POLICY "staff read all koica loans"
      ON koica_loans
      FOR SELECT
      TO authenticated
      USING (
        public.has_portal_role(auth.uid(), auth.email(), ARRAY[''manager'', ''bod'', ''bookkeeper''])
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all koica loans" ON koica_loans';
    EXECUTE '
      CREATE POLICY "service role all koica loans"
      ON koica_loans
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';

    EXECUTE 'DROP POLICY IF EXISTS "staff update koica workflow" ON koica_loans';
    EXECUTE '
      CREATE POLICY "staff update koica workflow"
      ON koica_loans
      FOR UPDATE
      TO authenticated
      USING (
        public.has_portal_role(auth.uid(), auth.email(), ARRAY[''manager'', ''bookkeeper''])
      )
      WITH CHECK (
        public.has_portal_role(auth.uid(), auth.email(), ARRAY[''manager'', ''bookkeeper''])
      )
    ';
  END IF;

END $$;

DO $$
BEGIN
  IF to_regclass('public.loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own loans" ON loans';
    EXECUTE '
      CREATE POLICY "authenticated insert own loans"
      ON loans
      FOR INSERT
      TO authenticated
      WITH CHECK (
        lower(coalesce(user_email, '''')) = lower(auth.email())
        AND member_id = auth.uid()
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own loans" ON loans';
    EXECUTE '
      CREATE POLICY "authenticated read own loans"
      ON loans
      FOR SELECT
      TO authenticated
      USING (
        lower(coalesce(user_email, '''')) = lower(auth.email())
        OR member_id = auth.uid()
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "staff read all loans" ON loans';
    EXECUTE '
      CREATE POLICY "staff read all loans"
      ON loans
      FOR SELECT
      TO authenticated
      USING (
        public.has_portal_role(
          auth.uid(),
          auth.email(),
          ARRAY[''manager'', ''bod'', ''bookkeeper'']
        )
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "manager update all loans" ON loans';
    EXECUTE 'DROP POLICY IF EXISTS "staff update loan workflow" ON loans';
    EXECUTE '
      CREATE POLICY "staff update loan workflow"
      ON loans
      FOR UPDATE
      TO authenticated
      USING (
        public.has_portal_role(auth.uid(), auth.email(), ARRAY[''manager'', ''bookkeeper''])
      )
      WITH CHECK (
        public.has_portal_role(auth.uid(), auth.email(), ARRAY[''manager'', ''bookkeeper''])
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "manager delete all loans" ON loans';
    EXECUTE '
      CREATE POLICY "manager delete all loans"
      ON loans
      FOR DELETE
      TO authenticated
      USING (
        public.has_portal_role(auth.uid(), auth.email(), ARRAY[''manager''])
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all loans" ON loans';
    EXECUTE '
      CREATE POLICY "service role all loans"
      ON loans
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;

  IF to_regclass('public.co_makers') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert co makers for own loan" ON co_makers';
    EXECUTE '
      CREATE POLICY "authenticated insert co makers for own loan"
      ON co_makers
      FOR INSERT
      TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.loans l
          WHERE l.control_number = co_makers.loan_id
            AND (lower(coalesce(l.user_email, '''')) = lower(auth.email()) OR l.member_id = auth.uid())
        )
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read co makers for own loan" ON co_makers';
    EXECUTE '
      CREATE POLICY "authenticated read co makers for own loan"
      ON co_makers
      FOR SELECT
      TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.loans l
          WHERE l.control_number = co_makers.loan_id
            AND (lower(coalesce(l.user_email, '''')) = lower(auth.email()) OR l.member_id = auth.uid())
        )
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all co makers" ON co_makers';
    EXECUTE '
      CREATE POLICY "service role all co makers"
      ON co_makers
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.member') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "staff read members" ON member';
    EXECUTE '
      CREATE POLICY "staff read members"
      ON member
      FOR SELECT
      TO authenticated
      USING (
        public.has_portal_role(
          auth.uid(),
          auth.email(),
          ARRAY[''manager'', ''bod'', ''bookkeeper'']
        )
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "member read own member profile" ON member';
    EXECUTE '
      CREATE POLICY "member read own member profile"
      ON member
      FOR SELECT
      TO authenticated
      USING (id = auth.uid())
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all members" ON member';
    EXECUTE '
      CREATE POLICY "service role all members"
      ON member
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.consolidated_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own consolidated loans" ON consolidated_loans';
    EXECUTE $policy$
      CREATE POLICY "authenticated insert own consolidated loans"
      ON consolidated_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (lower(coalesce(user_email, '')) = lower(auth.email()))
    $policy$;

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own consolidated loans" ON consolidated_loans';
    EXECUTE $policy$
      CREATE POLICY "authenticated read own consolidated loans"
      ON consolidated_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '')) = lower(auth.email()))
    $policy$;

    EXECUTE 'DROP POLICY IF EXISTS "service role all consolidated loans" ON consolidated_loans';
    EXECUTE $policy$
      CREATE POLICY "service role all consolidated loans"
      ON consolidated_loans
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role')
    $policy$;
  END IF;

  IF to_regclass('public.emergency_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own emergency loans" ON emergency_loans';
    EXECUTE $policy$
      CREATE POLICY "authenticated insert own emergency loans"
      ON emergency_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (lower(coalesce(user_email, '')) = lower(auth.email()))
    $policy$;

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own emergency loans" ON emergency_loans';
    EXECUTE $policy$
      CREATE POLICY "authenticated read own emergency loans"
      ON emergency_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '')) = lower(auth.email()))
    $policy$;

    EXECUTE 'DROP POLICY IF EXISTS "service role all emergency loans" ON emergency_loans';
    EXECUTE $policy$
      CREATE POLICY "service role all emergency loans"
      ON emergency_loans
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role')
    $policy$;
  END IF;

  IF to_regclass('public.bonus_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own bonus loans" ON bonus_loans';
    EXECUTE $policy$
      CREATE POLICY "authenticated insert own bonus loans"
      ON bonus_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (lower(coalesce(user_email, '')) = lower(auth.email()))
    $policy$;

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own bonus loans" ON bonus_loans';
    EXECUTE $policy$
      CREATE POLICY "authenticated read own bonus loans"
      ON bonus_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '')) = lower(auth.email()))
    $policy$;

    EXECUTE 'DROP POLICY IF EXISTS "service role all bonus loans" ON bonus_loans';
    EXECUTE $policy$
      CREATE POLICY "service role all bonus loans"
      ON bonus_loans
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role')
    $policy$;
  END IF;
END $$;
