-- Run this in Supabase SQL editor.
-- This file is for LOAN FORM RLS policies only.
-- It is intentionally separate from membership_confirmation_policies.sql.

ALTER TABLE IF EXISTS consolidated_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS emergency_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bonus_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS co_makers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS loan_types ENABLE ROW LEVEL SECURITY;

-- Co-maker schema support for both members and non-members.
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_name TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_email TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_mobile TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_address TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS co_maker_id_no TEXT;
ALTER TABLE IF EXISTS public.co_makers ADD COLUMN IF NOT EXISTS is_member BOOLEAN NOT NULL DEFAULT false;

DO $$
DECLARE
  existing_pk_name text;
BEGIN
  IF to_regclass('public.co_makers') IS NOT NULL THEN
    -- Drop any existing primary key (name can vary: co_makers_pk / co_makers_pkey / etc.).
    SELECT conname
    INTO existing_pk_name
    FROM pg_constraint
    WHERE conrelid = 'public.co_makers'::regclass
      AND contype = 'p'
    LIMIT 1;

    IF existing_pk_name IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.co_makers DROP CONSTRAINT %I', existing_pk_name);
    END IF;

    -- Backfill id for existing rows before creating new PK.
    EXECUTE 'UPDATE public.co_makers SET id = DEFAULT WHERE id IS NULL';

    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'co_makers_id_pk'
        AND conrelid = 'public.co_makers'::regclass
    ) THEN
      EXECUTE 'ALTER TABLE public.co_makers ADD CONSTRAINT co_makers_id_pk PRIMARY KEY (id)';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'co_makers'
        AND column_name = 'member_id'
        AND is_nullable = 'NO'
    ) THEN
      EXECUTE 'ALTER TABLE public.co_makers ALTER COLUMN member_id DROP NOT NULL';
    END IF;
  END IF;
END $$;

DROP INDEX IF EXISTS idx_co_makers_loan_member_unique;
CREATE INDEX IF NOT EXISTS idx_co_makers_loan_member_idx
ON public.co_makers (loan_id, member_id);

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON public.loan_types TO authenticated;
GRANT SELECT, INSERT ON public.loans TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.co_makers TO authenticated;

DO $$
BEGIN
  IF to_regclass('public.loan_types') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated read loan types" ON loan_types';
    EXECUTE 'CREATE POLICY "authenticated read loan types" ON loan_types FOR SELECT TO authenticated USING (true)';

    EXECUTE 'DROP POLICY IF EXISTS "service role all loan types" ON loan_types';
    EXECUTE 'CREATE POLICY "service role all loan types" ON loan_types FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')';
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own loans" ON loans';
    EXECUTE '
      CREATE POLICY "authenticated insert own loans"
      ON loans
      FOR INSERT
      TO authenticated
      WITH CHECK (
        lower(coalesce(user_email, '''')) = lower(auth.email())
        AND member_id = auth.uid()
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own loans" ON loans';
    EXECUTE '
      CREATE POLICY "authenticated read own loans"
      ON loans
      FOR SELECT
      TO authenticated
      USING (
        lower(coalesce(user_email, '''')) = lower(auth.email())
        OR member_id = auth.uid()
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all loans" ON loans';
    EXECUTE '
      CREATE POLICY "service role all loans"
      ON loans
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;

  IF to_regclass('public.co_makers') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert co makers for own loan" ON co_makers';
    EXECUTE '
      CREATE POLICY "authenticated insert co makers for own loan"
      ON co_makers
      FOR INSERT
      TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.loans l
          WHERE l.control_number = co_makers.loan_id
            AND (lower(coalesce(l.user_email, '''')) = lower(auth.email()) OR l.member_id = auth.uid())
        )
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read co makers for own loan" ON co_makers';
    EXECUTE '
      CREATE POLICY "authenticated read co makers for own loan"
      ON co_makers
      FOR SELECT
      TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.loans l
          WHERE l.control_number = co_makers.loan_id
            AND (lower(coalesce(l.user_email, '''')) = lower(auth.email()) OR l.member_id = auth.uid())
        )
      )
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all co makers" ON co_makers';
    EXECUTE '
      CREATE POLICY "service role all co makers"
      ON co_makers
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.consolidated_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own consolidated loans" ON consolidated_loans';
    EXECUTE '
      CREATE POLICY "authenticated insert own consolidated loans"
      ON consolidated_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own consolidated loans" ON consolidated_loans';
    EXECUTE '
      CREATE POLICY "authenticated read own consolidated loans"
      ON consolidated_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all consolidated loans" ON consolidated_loans';
    EXECUTE '
      CREATE POLICY "service role all consolidated loans"
      ON consolidated_loans
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;

  IF to_regclass('public.emergency_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own emergency loans" ON emergency_loans';
    EXECUTE '
      CREATE POLICY "authenticated insert own emergency loans"
      ON emergency_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own emergency loans" ON emergency_loans';
    EXECUTE '
      CREATE POLICY "authenticated read own emergency loans"
      ON emergency_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all emergency loans" ON emergency_loans';
    EXECUTE '
      CREATE POLICY "service role all emergency loans"
      ON emergency_loans
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;

  IF to_regclass('public.bonus_loans') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "authenticated insert own bonus loans" ON bonus_loans';
    EXECUTE '
      CREATE POLICY "authenticated insert own bonus loans"
      ON bonus_loans
      FOR INSERT
      TO authenticated
      WITH CHECK (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "authenticated read own bonus loans" ON bonus_loans';
    EXECUTE '
      CREATE POLICY "authenticated read own bonus loans"
      ON bonus_loans
      FOR SELECT
      TO authenticated
      USING (lower(coalesce(user_email, '''')) = lower(auth.email()))
    ';

    EXECUTE 'DROP POLICY IF EXISTS "service role all bonus loans" ON bonus_loans';
    EXECUTE '
      CREATE POLICY "service role all bonus loans"
      ON bonus_loans
      FOR ALL
      USING (auth.role() = ''service_role'')
      WITH CHECK (auth.role() = ''service_role'')
    ';
  END IF;
END $$;
